### ISSUE TITLE
Caliban crashes if one tries to resize its window by clicking on the corner

### ISSUE THREAD

**Issue by 6884** [vanvalenlab/deepcell-label#223]
**Describe the bug**
I touch the corner of Caliban's window => Caliban segfaults.

**To Reproduce**

1. ```python desktop/caliban.py desktop/examples/test.npz```
2. click on one corner of the window as to try resize it
3. ???
4. SEGFAULT!

**Expected behavior**
Not segfault. Possibly resize the window.

**Screenshots**
```
(base) stefano@Stefanos-MBP deepcell-label % python desktop/caliban.py desktop/examples/test.npz
desktop/caliban.py:1632: FutureWarning: `draw.circle` is deprecated in favor of `draw.disk`.`draw.circle` will be removed in version 0.19
  self.area = circle(self.y, self.x, self.size, (self.height,self.width))
desktop/caliban.py:188: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("viridis"))
  self.labels_cmap.set_bad('black')
Exception ignored on calling ctypes callback function: <function ObjCSubclass.method.<locals>.decorator.<locals>.objc_method at 0x7fbd107944c0>
Traceback (most recent call last):
  File "/Users/stefano/opt/anaconda3/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
    result = f(py_self, *args)
  File "/Users/stefano/opt/anaconda3/lib/python3.8/site-packages/pyglet/window/cocoa/pyglet_window.py", line 25, in nextEventMatchingMask_untilDate_inMode_dequeue_
    if self.inLiveResize():
  File "/Users/stefano/opt/anaconda3/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785, in __call__
    return self.method(self.objc_id, *args)
  File "/Users/stefano/opt/anaconda3/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 764, in __call__
    error.args += ('selector = ' + self.name,
TypeError: can only concatenate str (not "bytes") to str
zsh: segmentation fault  python desktop/caliban.py desktop/examples/test.npz
```

**Desktop (please complete the following information):**
 - osx 10.15.7
 - Python 3.8.5
 - not a desktop tbh

**Additional context**
hey people thanks a lot for this tool! I think it will be very useful to us.
Also, I didn't manage to run setup.py to install all the dependencies at once :(

**Comment by geneva-miller** [comment]
Hi Stefano, that's definitely not an error I've seen before! I think the best first step towards resolving this issue will be to make sure your dependencies are installed correctly. Could you post the output from when you tried to run `setup.py`? I would also recommend using a virtual environment to help make sure the correct versions of packages are installed for using this program.

**Comment by 6884** [comment]
Hi Geneva, thanks for your help! (and for the presentation at I2K, I was very lucky to be admitted and to find out about deepcell)
 
So, the problem that made me abandon the setup.py route was this:

`error: SandboxViolation: mkdir('/Users/stefano/.matplotlib', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.`

I tried looking for workarounds but no luck :( It doesn't help that I am quite a newbie at Python...

I'm attaching the whole log of the install command, should it be of any help.

[deepcell_install.txt](https://github.com/vanvalenlab/deepcell-label/files/5872107/deepcell_install.txt)

Thanks again!

**Comment by geneva-miller** [comment]
I'm not familiar with EasyInstall and whatever might be going on here. I would try using pip to install the required packages from the `requirements.txt` file in the repository into your active virtual environment. I think `setup.py` is for running DeepCell Label with Docker and not something you need to run.
