### ISSUE TITLE
Permission error when running caliban.py

### ISSUE THREAD

**Issue by Jeff-Gui** [vanvalenlab/deepcell-label#233]
**Describe the bug**
Permission error when running caliban.py and trying to save edited tracks.

**To Reproduce**
1. Run python caliban.py examples/trackfile1.trk
2. Click S to save
3. See error message
`
Unexpected error saving file.
Traceback (most recent call last):
  File "caliban.py", line 3026, in save
    trks.add(lineage_file.name, "lineage.json")
  File "anaconda3\envs\dclabel\lib\tarfile.py", line 1939, in add
    with bltn_open(name, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\CELLDI~1\\AppData\\Local\\Temp\\tmphs3mhagm'
`
4. Run as administrator does not help

**Expected behavior**
Saved successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version [e.g. 3.5]

**Comment by geneva-miller** [comment]
At a glance, I think this may be due to the python `tempfile` module, which does not always work correctly on Windows. Are you running `caliban.py` within a Docker container?

**Comment by Jeff-Gui** [comment]
I guess so. When running Docker container everything is ok, but running on the host fails.
