### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by aysanaghazadeh** [vanvalenlab/deepcell-label#328]
Hello,

I'm trying to run the deepcell_label locally by running python backend but there is a problem with connecting to DB. I went through the readme file to run the flask.

The error is:
sqlite3.OperationalError: unable to open database file

Which is the direct cause of:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

I would appreciate it if you could help me with this issue.

**Comment by msschwartz21** [comment]
Hi Aysan,

I think that if you comment out these two lines in your config files (that do not have the `.example` extension) it may solve the problem: 
https://github.com/vanvalenlab/deepcell-label/blob/9e1cdba30732084f4e6b8794ae3faf805e359ede/fmd_config.cfg.example#L19
https://github.com/vanvalenlab/deepcell-label/blob/9e1cdba30732084f4e6b8794ae3faf805e359ede/.env.example#L12

If that doesn't work, please let us know. I'm sure @tddough98 can give you a more definitive answer.

**Comment by aysanaghazadeh** [comment]
Hello,

Thank you so much for your response.

Unfortunately, I get the same the error:
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''

I would appreciate it if you could help me with the issue.

Thank you again and best regards,
Aysan

**Comment by tddough98** [comment]
Hi @aysanaghazadeh, `sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''`is the error we've seen when  SQLALCHEMY_DATABASE_URI= is not set and not commented out in the `.env` file.  To make sure that there's no issue there, here's a complete `.env` you can paste in and use

```
# Flask settings
FLASK_APP=application
FLASK_ENV=development
# DEBUG=
# TEMPLATES_AUTO_RELOAD=

# AWS credentials
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=

# SQL Alchemy settings
# SQLALCHEMY_DATABASE_URI=
# SQLALCHEMY_TRACK_MODIFICATIONS=

# Flask monitoring dashboard
# DASHBOARD_CONFIG=
```

If you're still seeing the same error, try explicitly setting SQLALCHEMY_DATABASE_URI in `.env` to it's default value with 
```
SQLALCHEMY_DATABASE_URI=sqlite:////tmp/deepcell_label.db
```

Please let us know if you continue to have errors or issues and I'll be happy to help out further. I'll update the `.env.example` to comment out the empty fields to try to prevent this from happening with other users too.

**Comment by aysanaghazadeh** [comment]
Thank you so much. 

It worked, and the errors are resolved. 

Also, to setup the front-end I went through the readme file again; however, I got this error:
Command: node-pre-gyp install --fallback-to-build on canvas failed.

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/DeepCell/deepcell-label/visualizer/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd DeepCell/deepcell-label/visualizer/node_modules/canvas
gyp ERR! node -v v18.2.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=DeepCell/deepcell-label/visualizer/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/DeepCell/deepcell-label/visualizer/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "DeepCell/deepcell-label/visualizer/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /DeepCell/deepcell-label/visualizer/node_modules/canvas
node-pre-gyp ERR! node -v v18.2.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
Failed to execute 'DeepCell/deepcell-label/visualizer/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ays

I would appreciate it if you could help me with this issue too.
